[settings]
is-active = true
database = "frog_uhm"
table = "reading"
primary-key = ["datetime","purpose_id"]
save-duplicates = true


[conversions]
datetime = "to-timestamp"
upload_timestamp = "to-timestamp"
