[acquire.static.settings]
is-active = true
source = '/usr/local/scrape-util/hobo-u12/inputs/'
on-fmt = '/usr/local/scrape-util/hobo-u12/archive/'
on-err = '/usr/local/scrape-util/hobo-u12/errors/'
on-raw = '/usr/local/scrape-util/hobo-u12/raws/' # default: `false`


[[acquire.static.parser]]
parser = "hobo-u12-csv"
suffix = "csv"


# VALUE RESHAPING
[reshape]
# the value-based reshaping configurations have been
# moved to `value-map.toml` for clarity/organization.
value-file = "value-map"

# FIELD RESHAPING
[reshape.field.settings]
is-active = true
on-modify = "discard" # "discard" || "archive"
in-order = ["modify","generate"] # default: ["modify","generate"]

[reshape.field.modify]
name = { title = "purpose_id", index = 1, type = "int" }
unit = { title = "units", index = 2, type = "str" }
value = { title = "reading", index = 3, type = "float" }
timestamp = { title = "datetime", index = 0, type = "int" }

[[reshape.field.generate]]
value = "current-time"
title = "upload_timestamp"
index = "append" # default: "append"
round = 2 # default: 6


# EXPORT CONFIGURATIONS

# CSV EXPORT
[export.csv.settings]
is-active = true
directory = '/usr/local/scrape-util/hobo-u12/outputs/'
file-spec = { tag = 'u12-data', timestamp = true }

# PSQL EXPORT
[export.psql.settings]
is-active = true
database = "maui"
table = "reading"
primary-key = ["datetime","purpose_id"]

[export.psql.conversions]
datetime = "to-timestamp"
upload_timestamp = "to-timestamp"
