# This file contains the mappings for value-based
# reshapings to be performed on the hobo-u12 data
# acquired during the maui smart grid project.


# GENERAL CONFIGURATIONS
[settings]
is-active = true
to-replace = ["name","unit"]
uid-key = ["node","name"]
in-order = ["filter","replace"]


# VALUE-BASED FILTERING
[filter]
# round all timestamps to nearest whole number,
# and filter out any which are not on the minute
# mark (ending in `00.0`).
#timestamp = { dec = 0, tail = "00.0" }


# VALUE-BASED REPLACEMENT
[replace]
hobo-9790178-intensity = [ "129", "lum/ft2",]
hobo-9790169-rh = [ "68", "%",]
hobo-9790168-intensity = [ "114", "lum/ft2",]
hobo-9790174-rh = [ "87", "%",]
hobo-9790177-temp = [ "32", "F",]
hobo-10688124-temp = [ "43", "F",]
hobo-9796095-temp = [ "12", "F",]
hobo-9796120-rh = [ "72", "%",]
hobo-9790174-temp = [ "42", "F",]
hobo-9796108-intensity = [ "109", "lum/ft2",]
hobo-9790157-intensity = [ "111", "lum/ft2",]
hobo-9796064-rh = [ "47", "%",]
hobo-9796120-intensity = [ "117", "lum/ft2",]
hobo-9796090-intensity = [ "99", "lum/ft2",]
hobo-9790167-intensity = [ "126", "lum/ft2",]
hobo-9796094-rh = [ "58", "%",]
hobo-9796067-temp = [ "3", "F",]
hobo-9796076-temp = [ "6", "F",]
hobo-10688124-rh = [ "88", "%",]
hobo-9790179-rh = [ "83", "%",]
hobo-9790170-rh = [ "75", "%",]
hobo-9796092-intensity = [ "104", "lum/ft2",]
hobo-9790160-rh = [ "71", "%",]
hobo-9796094-temp = [ "13", "F",]
hobo-9796112-intensity = [ "125", "lum/ft2",]
hobo-9796099-intensity = [ "106", "lum/ft2",]
hobo-9796119-intensity = [ "127", "lum/ft2",]
hobo-9790171-temp = [ "45", "F",]
hobo-9790174-intensity = [ "132", "lum/ft2",]
hobo-9790169-intensity = [ "113", "lum/ft2",]
hobo-9796069-intensity = [ "130", "lum/ft2",]
hobo-9790160-temp = [ "26", "F",]
hobo-9796092-rh = [ "59", "%",]
hobo-9796089-rh = [ "53", "%",]
hobo-9796062-rh = [ "46", "%",]
hobo-9790168-temp = [ "24", "F",]
hobo-9796087-temp = [ "7", "F",]
hobo-9796064-intensity = [ "92", "lum/ft2",]
hobo-9790177-rh = [ "77", "%",]
hobo-9790159-rh = [ "70", "%",]
hobo-9796077-intensity = [ "100", "lum/ft2",]
hobo-9796108-rh = [ "64", "%",]
hobo-9790166-rh = [ "73", "%",]
hobo-9796074-intensity = [ "94", "lum/ft2",]
hobo-9790159-intensity = [ "115", "lum/ft2",]
hobo-9796119-temp = [ "37", "F",]
hobo-9796095-rh = [ "57", "%",]
hobo-9796112-rh = [ "80", "%",]
hobo-9790158-rh = [ "67", "%",]
hobo-9790179-temp = [ "38", "F",]
hobo-10688122-intensity = [ "131", "lum/ft2",]
hobo-9796076-rh = [ "51", "%",]
hobo-9796109-intensity = [ "119", "lum/ft2",]
hobo-9796096-temp = [ "15", "F",]
hobo-9790170-intensity = [ "120", "lum/ft2",]
hobo-9796070-intensity = [ "95", "lum/ft2",]
hobo-9790176-rh = [ "76", "%",]
hobo-9790160-intensity = [ "116", "lum/ft2",]
hobo-9796064-temp = [ "2", "F",]
hobo-9796109-temp = [ "29", "F",]
hobo-9796067-intensity = [ "93", "lum/ft2",]
hobo-9790159-temp = [ "25", "F",]
hobo-10688122-rh = [ "86", "%",]
hobo-9796069-rh = [ "85", "%",]
hobo-9790166-intensity = [ "118", "lum/ft2",]
hobo-9790157-temp = [ "21", "F",]
hobo-9796090-temp = [ "9", "F",]
hobo-9790179-intensity = [ "128", "lum/ft2",]
hobo-9790178-rh = [ "84", "%",]
hobo-9796093-rh = [ "56", "%",]
hobo-9796067-rh = [ "48", "%",]
hobo-9796104-temp = [ "20", "F",]
hobo-9790175-temp = [ "33", "F",]
hobo-9796099-rh = [ "61", "%",]
hobo-9796062-intensity = [ "91", "lum/ft2",]
hobo-9796111-temp = [ "18", "F",]
hobo-9790176-temp = [ "31", "F",]
hobo-9796077-temp = [ "10", "F",]
hobo-9790171-rh = [ "90", "%",]
hobo-9790169-temp = [ "23", "F",]
hobo-9790178-temp = [ "39", "F",]
hobo-9790176-intensity = [ "121", "lum/ft2",]
hobo-9796073-rh = [ "89", "%",]
hobo-9796100-temp = [ "17", "F",]
hobo-9796090-rh = [ "54", "%",]
hobo-9796087-rh = [ "52", "%",]
hobo-9790175-intensity = [ "123", "lum/ft2",]
hobo-9796104-rh = [ "65", "%",]
hobo-9796096-rh = [ "60", "%",]
hobo-9790177-intensity = [ "122", "lum/ft2",]
hobo-9796070-temp = [ "5", "F",]
hobo-9796120-temp = [ "27", "F",]
hobo-9796089-temp = [ "8", "F",]
hobo-9796092-temp = [ "14", "F",]
hobo-9796104-intensity = [ "110", "lum/ft2",]
hobo-9796073-temp = [ "44", "F",]
hobo-9790170-temp = [ "30", "F",]
hobo-9796118-temp = [ "34", "F",]
hobo-9796109-rh = [ "74", "%",]
hobo-9796077-rh = [ "55", "%",]
hobo-9796073-intensity = [ "134", "lum/ft2",]
hobo-9790175-rh = [ "78", "%",]
hobo-9796111-intensity = [ "108", "lum/ft2",]
hobo-9796112-temp = [ "35", "F",]
hobo-9790158-intensity = [ "112", "lum/ft2",]
hobo-9796118-intensity = [ "124", "lum/ft2",]
hobo-9796100-rh = [ "62", "%",]
hobo-9796070-rh = [ "50", "%",]
hobo-9796100-intensity = [ "107", "lum/ft2",]
hobo-10688122-temp = [ "41", "F",]
hobo-9796069-temp = [ "40", "F",]
hobo-9790167-rh = [ "81", "%",]
hobo-9796093-temp = [ "11", "F",]
hobo-9796108-temp = [ "19", "F",]
hobo-9796089-intensity = [ "98", "lum/ft2",]
hobo-9796094-intensity = [ "103", "lum/ft2",]
hobo-9796087-intensity = [ "97", "lum/ft2",]
hobo-9796099-temp = [ "16", "F",]
hobo-9790171-intensity = [ "135", "lum/ft2",]
hobo-9796074-temp = [ "4", "F",]
hobo-10688124-intensity = [ "133", "lum/ft2",]
hobo-9796062-temp = [ "1", "F",]
hobo-9790158-temp = [ "22", "F",]
hobo-9796076-intensity = [ "96", "lum/ft2",]
hobo-9790157-rh = [ "66", "%",]
hobo-9796111-rh = [ "63", "%",]
hobo-9796093-intensity = [ "101", "lum/ft2",]
hobo-9790168-rh = [ "69", "%",]
hobo-9796096-intensity = [ "105", "lum/ft2",]
hobo-9796119-rh = [ "82", "%",]
hobo-9796118-rh = [ "79", "%",]
hobo-9796095-intensity = [ "102", "lum/ft2",]
hobo-9790166-temp = [ "28", "F",]
hobo-9796074-rh = [ "49", "%",]
hobo-9790167-temp = [ "36", "F",]
